name: Astrolabe CI Check
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code of astrolabe
        uses: actions/checkout@v2
        with:
          path: src/github.com/vmware-tanzu/astrolabe
      - name: Make CI
        env:
          GOPATH: ${{ github.workspace }}
        run: |
          cd src/github.com/vmware-tanzu/astrolabe
          make
