name: Astrolabe CI Check
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code of astrolabe
        uses: actions/checkout@v2
        with:
          path: src/github.com/vmware-tanzu/astrolabe
      - name: Download essential GVDDK libraries
        run: |
          cd /tmp
          wget --quiet https://gvddk-libs.s3-us-west-1.amazonaws.com/VMware-vix-disklib-7.0.2-17696664.x86_64.tar.gz
          cd /usr/local
          sudo tar xzf /tmp/VMware-vix-disklib-7.0.2-17696664.x86_64.tar.gz
          sudo chmod 644 $(find vmware-vix-disklib-distrib/lib64/ -type f)
      - name: Make CI
        env:
          GOPATH: ${{ github.workspace }}
        run: |
          cd src/github.com/vmware-tanzu/astrolabe
          make
